eu_countries: dict[str, str] = {
    'EA20': 'Euro area - 20 countries (from 2023)',
    'DE': 'Germany (until 1990 former territory of the FRG)',
    'FR': 'France',
    'IT': 'Italy',
    'ES': 'Spain',
    'BE': 'Belgium',
    'AT': 'Austria',
    'NL': 'Netherlands',
    'SE': 'Sweden',
    'DK': 'Denmark',
    'FI': 'Finland',
    'PT': 'Portugal',
    'EL': 'Greece',
    'PL': 'Poland',
    'IE': 'Ireland',
    'TR': 'Turkey',
}